### ISSUE TITLE
A new deployment-ready rabbitmq cluster for kubernetes 1.5.x

### ISSUE THREAD

**Issue by erez-rabih** [mdevilliers/kubernetes-rabbitmq-cluster#1]
Hi,

Just wanted to note that we've open sourced a new, deployment-ready rabbitmq cluster for kubernetes 1.5.x which uses StatefulSets

You can find it here https://github.com/nanit/kubernetes-rabbitmq-cluster

**Comment by mdevilliers** [comment]
Awesome - I'll check it out.

Thanks

**Comment by erez-rabih** [comment]
@mdevilliers If you find it working, maybe it is worth to reference to from the README...

**Comment by mdevilliers** [comment]
NP - I've added it!

Good luck with your project!
